# Generated by Django 5.1 on 2024-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=49)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
