# Generated by Django 5.1 on 2024-08-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
    ]
