# Generated by Django 5.1 on 2024-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_bank_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('name', models.CharField(blank=True, max_length=49, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
